---
#  /*! @brief Abstracted RW array configuration input. */
#  typedef struct {
#      int numRW; /*!< Number of active reaction wheels */
#  } RWArrayConfigInput_c;
fields:
  - name: Num_Rw
    type: Interfaces.Integer_32
    format: I32
    description: "[-] Number of active reaction wheels"
