---
#  /*! @brief Abstracted vehicle configuration input. */
#  typedef struct {
#      float ISCPntB_B[9]; /*!< Inertia tensor about SC body point B, body frame (kg*m^2), column-major */
#      float massSC;       /*!< Spacecraft mass (kg) */
#  } VehicleConfigInput_c;
fields:
  - name: Iscpnt_B_B
    type: Packed_F32x9.T
    description: "[kg*m^2] Inertia tensor about SC body point B in body frame, column-major"
  - name: Mass_Sc
    type: Short_Float
    format: F32
    description: "[kg] Spacecraft mass"
