---
#  typedef struct {
#      float ISCPntB_B[9];         //!< [kg m^2] Spacecraft Inertia
#      float CoM_B[3];             //!< [m] Center of mass of spacecraft in body
#      float massSC;               //!< [kg] Spacecraft mass
#      uint32_t CurrentADCSState;  //!< [-] Current ADCS state for subsystem
#  } VehicleConfigMsgF32Payload;
description: Structure used to define a common structure for top level vehicle information
fields:
  - name: Iscpnt_B_B
    type: Packed_F32x9.T
    description: "[kg m^2] Spacecraft Inertia (9 elements, 3x3 matrix in row-major order)"
  - name: Co_M_B
    type: Packed_F32x3.T
    description: "[m] Center of mass of spacecraft in body"
  - name: Mass_Sc
    type: Short_Float
    format: F32
    description: "[kg] Spacecraft mass"
  - name: Current_Adcsstate
    type: Interfaces.Unsigned_32
    format: U32
    description: "[-] Current ADCS state for subsystem"
